In [ ]:
# 리스트로 만들고 정렬 1:1로 맞아떨어진다...?
words = ['eat', 'tea', 'tan', 'ate', 'nat', 'bat']